export const GET_ASSESSMENTS_REQUEST = 'GET_ASSESSMENTS_REQUEST';
export const GET_ASSESSMENTS_SUCCESS = 'GET_ASSESSMENTS_SUCCESS';
export const GET_ASSESSMENTS_FAILURE = 'GET_ASSESSMENTS_FAILURE';

export const CREATE_ASSESSMENT_REQUEST = 'CREATE_ASSESSMENT_REQUEST';
export const CREATE_ASSESSMENT_SUCCESS = 'CREATE_ASSESSMENT_SUCCESS';
export const CREATE_ASSESSMENT_FAILURE = 'CREATE_ASSESSMENT_FAILURE';
